### ISSUE TITLE
Impossible puzzle

### ISSUE THREAD

**Issue by RoboMWM** [NiklasEi/logic-puzzles-for-gamebox#2]
I haven't looked at it myself yet but @frostalf reported an issue with a sudoku game he was given. 

![](https://i.imgur.com/h0tUaVh.jpg)

**Comment by NiklasEi** [comment]
The puzzle looks solvable to me. There might be a mistake in the upper middle block: at the current state of the puzzle the 1 and the 9 can be switched... These are not placeable jet and could be wrong.
@frostalf what exactly is the problem with the puzzle?

**Comment by frostalf** [comment]
The problem with the puzzle revolves around the top portion and a horizontal portion. You can't place a 1 in the right corner because horizontally at the bottom right there is a 1 already. So once we place the 1 where it should go, top center kind of, next on that same line with the 1 but horizontal, we will place a 3 in the only spot in can go, towards the bottom. Next we will place the 6 next to the 3. This is where the problem arises. You also need to place an 8, but the only available line there is already an 8 vertically. If you tried to switch the 6 and the 8, there is also a 6 vertically. This makes the puzzle not solvable since the whole point of sudoku is to not have duplicate numbers going horizontal or vertically.

[Impossible Sudoku Puzzle](https://imgur.com/a/Iw7pUgy)

**Comment by NiklasEi** [comment]
I couldn't really follow that, but I just sat down and solved it:
![20180626_155319](https://user-images.githubusercontent.com/12236672/41916901-69a859f0-7959-11e8-8b15-cdbb627d9f71.jpg)

As I said in my last comment, the 9 and 1 that you placed in the middle column top row, cannot be placed with the info you have at that state. If you check my solution, they have to be switched.
